[build]
  builder = "nixpacks"
  buildCommand = "npm install && npm run build && php artisan route:clear && php artisan view:clear && php artisan config:clear"

[deploy]
  startCommand = "php artisan migrate --force && php artisan config:cache && vendor/bin/heroku-php-apache2 public/"
  healthcheckPath = "/login"
  healthcheckTimeout = 120
  restartPolicyType = "on_failure"
  restartPolicyMaxRetries = 5

[variables]
  APP_DEBUG = "false"
  LOG_CHANNEL = "stderr"
  NIXPACKS_PHP_VERSION = "8.2"
