[build]
  builder = "nixpacks"
  buildCommand = "npm install && npm run build && php artisan route:clear && php artisan view:clear"

[deploy]
  startCommand = "php artisan config:cache && php artisan serve --host=0.0.0.0 --port $PORT"
  postDeploy = "php artisan cache:clear"

[variables]
  APP_DEBUG = "true"
