[build]
  builder = "nixpacks"
  buildCommand = "npm install && npm run build && php artisan route:clear && php artisan view:clear && php artisan storage:link && php artisan horizon:install"

[deploy]
  startCommand = "railway start"
  postDeploy = "php artisan cache:clear"

[variables]
  APP_DEBUG = "true"