[build]
  builder = "nixpacks"
  buildCommand = "npm install && npm run build && mkdir -p /usr/local/etc/php/conf.d && cp docker/php/99-upload.ini /usr/local/etc/php/conf.d/ && php artisan route:clear && php artisan view:clear && php artisan horizon:install"

[deploy]
  startCommand = "php artisan storage:link && php artisan config:cache && php artisan horizon & php artisan schedule:work & php artisan serve --host=0.0.0.0 --port $PORT"
  postDeploy = "php artisan cache:clear && php artisan horizon"

[variables]
  APP_DEBUG = "true"