# services/horizon/railway.toml
# — Servicio que ejecuta exclusivamente Laravel Horizon —

[build]
builder = "nixpacks"
buildCommand = "composer install --no-dev --prefer-dist --optimize-autoloader"

[deploy]
startCommand = "php artisan config:clear && php artisan tinker && php artisan horizon"
